Repository trace4cats/trace4cats-datadog, pull requests merged in 2021-07, with the labels that each got.

#6 Update Mergify rules
  .github/mergify.yml
Labels: skip-changelog

#12 Update sbt-ci-release-early to 2.0.17
  project/plugins.sbt
Labels: dependency-update

#13 Update sbt-scalafmt to 2.4.3
  project/plugins.sbt
Labels: dependency-update

#14 Update sbt to 1.5.5
  project/build.properties
Labels: dependency-update

#15 Add Scala 3 build
  .github/mergify.yml
  .github/workflows/ci.yml
  ci-release.sbt
  modules/datadog-http-exporter/src/main/scala/io/janstenpickle/trace4cats/datadog/DataDogSpan.scala
  modules/datadog-http-exporter/src/test/scala/io/janstenpickle/trace4cats/datadog/DataDogSpanExporterSpec.scala
  project/Dependencies.scala
Labels: enhancement
